In [ ]:
%pip install prepro-auto==3.0.0

In [3]:
%pip show prepro-auto

Name: prepro-auto
Version: 3.0.0
Summary: AI-assisted, human-in-the-loop preprocessing for tabular and time-series data — profile, clean, transform, forecast and export, with a reproducible pipeline, from a notebook or the web.
Home-page: https://github.com/Chilliflex/prepro_auto
Author: Shivanshu Pandey
Author-email:
License-Expression: MIT
Location: c:\Users\pande\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: fastapi, nest-asyncio, numpy, openpyxl, pandas, psutil, pyarrow, pydantic, pydantic-settings, python-dotenv, python-multipart, reportlab, scikit-learn, scipy, sqlalchemy, uvicorn, xlrd
Required-by:
Note: you may need to restart the kernel to use updated packages.

## Way to give Input

In [7]:
#1st way to give input file path
import prepro_auto

session =prepro_auto.launch_file(r"Bengaluru_House_Data.csv", domain="general", dataset_type="tabular", port=None, open_browser=False)

# Open this exact URL; another upload or launch creates a different job.
print(session.url)
# To resume an edited UI job, use its Copy notebook connection button instead.

16:09:16 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
Read Bengaluru_House_Data.csv: shape=(13320, 9), dtypes={'area_type': 'str', 'availability': 'str', 'location': 'str', 'size': 'str', 'society': 'str'}, ...
PrePro Auto workbench ready (your dataset is already loaded):
  http://127.0.0.1:8721/workbench?job=89133a50-281f-4bd2-8cfa-235f284d09f4
Use this exact URL for notebook sync. Each launch_file() call or UI upload creates a separate job.
http://127.0.0.1:8721/workbench?job=89133a50-281f-4bd2-8cfa-235f284d09f4

In [8]:
#2nd way to give input.
import os
os.environ["DEBUG"] = "false"

from pathlib import Path
import pandas as pd
import prepro_auto

path = Path(
    r"Bengaluru_House_Data.csv"
)

session = prepro_auto.launch_file(path, open_browser=True)

# Open this exact URL; another upload or launch creates a different job.
print(session.url)
# To resume an edited UI job, use its Copy notebook connection button instead.

16:09:18 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
Read Bengaluru_House_Data.csv: shape=(13320, 9), dtypes={'area_type': 'str', 'availability': 'str', 'location': 'str', 'size': 'str', 'society': 'str'}, ...
PrePro Auto workbench ready (your dataset is already loaded):
  http://127.0.0.1:8721/workbench?job=cc0251dc-bc88-40fa-8c03-c2e289d49ace
Use this exact URL for notebook sync. Each launch_file() call or UI upload creates a separate job.
http://127.0.0.1:8721/workbench?job=cc0251dc-bc88-40fa-8c03-c2e289d49ace

16:09:19 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
16:09:19 | INFO    | app.services.profiling_service | Profiled cc0251dc quality=86.6 shape=(13320,9)
16:09:19 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
16:09:19 | INFO    | app.api.routes.datasets | Preview generated: job=cc0251dc shape=(13320, 9)

In [ ]:
result = prepro_auto.quickclean(session, apply_all=True, verbose=False)
display(result.df.head())
print(result)

16:09:42 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
16:09:42 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
16:09:42 | INFO    | app.services.missing_value_service | Missing-value stage for cc0251dc: 5 cards (0 auto-approved, 5 pending).
16:09:43 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
16:09:43 | INFO    | app.services.versioning_service | Committed v1 for cc0251dc (missing_values) shape=(13320,10)
16:09:43 | INFO    | app.services.execution_service | Executed stage 'missing_values' for cc0251dc: 5 applied, 0 pending-skipped, snapshot v1 shape=(13320,10)
16:09:45 | INFO    | app.services.outlier_service | Outlier stage for cc0251dc: 4 cards (0 auto-approved, 4 pending).
16:09:45 | INFO    | app.services.versioning_service | Committed v2 for cc0251dc (outliers) shape=(13320,10)
16:09:45 | INFO    | app.services.execution_service | Executed stage 'outliers' for cc0251dc: 4 applied, 0 pending-skipped, snapshot v2 shape=(13320,10)
16:09:45 | INFO    | app.services.scaling_service | Scaling stage for cc0251dc: 4 cards (1 auto).
16:09:45 | INFO    | app.services.versioning_service | Committed v3 for cc0251dc (scaling) shape=(13320,10)
16:09:45 | INFO    | app.services.execution_service | Executed stage 'scaling' for cc0251dc: 4 applied, 0 pending-skipped, snapshot v3 shape=(13320,10)
16:09:45 | INFO    | app.services.scaling_service | Correlation stage for cc0251dc: 0 pair(s), 1 leakage finding(s).
16:09:45 | INFO    | app.services.versioning_service | Committed v4 for cc0251dc (correlation) shape=(13320,9)
16:09:45 | INFO    | app.services.execution_service | Executed stage 'correlation' for cc0251dc: 1 applied, 0 pending-skipped, snapshot v4 shape=(13320,9)
16:09:45 | INFO    | app.services.encoding_service | Encoding stage for cc0251dc: 3 cards (0 auto).
16:09:45 | INFO    | app.services.versioning_service | Committed v5 for cc0251dc (encoding) shape=(13320,12)
16:09:45 | INFO    | app.services.execution_service | Executed stage 'encoding' for cc0251dc: 3 applied, 0 pending-skipped, snapshot v5 shape=(13320,12)

,availability,location,size,society,total_sqft,bath,balcony,price,area_type_Built-up Area,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
0,0.013889,Electronic City Phase II,0.391517,Coomee,1056,0.0,-0.736810,-1.116176,0,0,0,1
1,0.794369,Chikka Tirupathi,0.062012,Theanmp,2600,3.0,1.750471,0.727295,0,0,1,0
2,0.794369,Uttarahalli,0.323574,GrrvaGr,1440,0.0,1.750471,-0.340890,1,0,0,0
3,0.794369,Lingadheeranahalli,0.323574,Soiewre,1521,1.0,-0.736810,0.354744,0,0,0,1
4,0.794369,Kothanur,0.391517,GrrvaGr,1200,0.0,-0.736810,-0.665897,0,0,0,1

PrePro Auto - quickclean report
  shape:          (13320, 9)  ->  (13320, 12)
  missing cells:  6201  ->  0
  actions applied: 17
  left for review: 0
  mode:           apply all recommendations
  stages:
    - missing_values found 5    applied 5    review 0
    - outliers       found 4    applied 4    review 0
    - scaling        found 4    applied 4    review 0
    - correlation    found 1    applied 1    review 0
    - encoding       found 3    applied 3    review 0

16:10:47 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
16:10:48 | INFO    | app.services.profiling_service | Profiled cc0251dc quality=86.6 shape=(13320,9)
16:10:48 | INFO    | app.services.file_reader | CSV read with encoding=utf-8-sig, shape=(13320, 9)
16:10:48 | INFO    | app.api.routes.datasets | Preview generated: job=cc0251dc shape=(13320, 9)
16:10:48 | INFO    | app.services.missing_value_service | Missing-value stage for cc0251dc: 0 cards (0 auto-approved, 0 pending).
16:11:06 | INFO    | app.services.versioning_service | Committed v6 for cc0251dc (transform:batch(1)) shape=(13320,5)
16:11:06 | INFO    | app.services.transform_service | Batch transform on cc0251dc: 1 step(s), (13320, 12) -> (13320, 5), v6
16:11:32 | INFO    | app.services.versioning_service | Committed v7 for cc0251dc (transform:batch(1)) shape=(13320,5)
16:11:32 | INFO    | app.services.transform_service | Batch transform on cc0251dc: 1 step(s), (13320, 5) -> (13320, 5), v7

In [12]:
df = session.current()
print(df.shape)
display(df.head())

PrePro Auto: 4 decision(s) in correlation, encoding are settled in the UI but have not been executed, so they are NOT in this dataframe. Click 'Execute stage' in the workbench, then call current() again.
(13320, 5)

                   location  total_sqft  bath   price  size
0  Electronic City Phase II      1056.0     2   39.07     2
1          Chikka Tirupathi      2600.0     5  120.00     4
2               Uttarahalli      1440.0     2   62.00     3
3        Lingadheeranahalli      1521.0     3   95.00     3
4                  Kothanur      1200.0     2   51.00     2

In [13]:
import pandas as pd
df['bath'] = df['bath'].astype(int)

In [14]:
session.update(df)

16:34:15 | INFO    | app.services.versioning_service | Committed v9 for cc0251dc (notebook_edit) shape=(13320,5)
PrePro Auto: pushed v9 (13320 rows x 5 cols) — the open workbench tab will refresh automatically.

In [16]:
df = session.current()
print(df.shape)
display(df.head())

(13320, 5)

                   Location  total_sqft  Bath   Price  Bedroom
0  Electronic City Phase II      1056.0     2   39.07        2
1          Chikka Tirupathi      2600.0     5  120.00        4
2               Uttarahalli      1440.0     2   62.00        3
3        Lingadheeranahalli      1521.0     3   95.00        3
4                  Kothanur      1200.0     2   51.00        2